### PR TITLE
Fix persist data storage blocking the csa

### LINKED ISSUE #21: Writing persist files blocks control system adapter
I just tested an application using the latest ControlsystemAdapter. I saw that my LabView client panels got stuck periodically. This is related to writing the persist file. I checked this by changing the persist file writing period. 

By removing the following lock: https://github.com/ChimeraTK/ControlSystemAdapter/blob/b2bd4a34488dc8af6da36398fac707a9c232a440/include/ChimeraTK/ControlSystemAdapter/PersistentDataStorage.h#L139
and removing related `lock` calls the client application was no longer affected by persist file write actions.

I did not yet invest how the client can be affected by writing the persist file and using that lock.

### PR DESCRIPTION
**Pull request by zenker**
The latest version fixes #21. I'm not sure if we can accept removing the lock_guard and using the lock directly. Else handling the reference becomes a bit unhandy.

### CODE REVIEW

**Comment by mhier** [comment]
Exceptions are not properly handled like this. I don't understand why you don't want to use the `lock_guard` here. Just place it together with the `read_latest()` inside an extra scope:
```
{
  std::lock_guard<std::mutex> lock(_queueReadMutex);
  std::vector<DataType>& value = boost::fusion::at_key<DataType>(_dataMap.table)[id].read_latest();
}
```

`read_latest()` can throw exceptions, either if they are written to the queue (which we currently don't do, but how knows what we do in future), or it throws a `std::system_error` in case the semaphore has an error. The second is already a case we shouldn't ignore.

**Comment by zenker** [comment]
Ok so now I use the lock_guard. I was not sure if the object that corresponds to the reference returned by `read_latest()` still exists after the block with the lock_guard. But since it is a reference to the `_dataMap` it is ok to use the pointer after closing the block.

**Comment by mhier** [comment]
A reference never extends the life time of an object :-)

**Comment by zenker** [comment]
You should also add a new tag 01.05.03, since I changed the version in the CMakeLists.txt.

**Comment by mhier** [comment]
Since there are other changes we have to release the current master as 01.06.00. This needs to wait until we have fixed a few issues in ApplicationCore and I think the release should be done together.

**Comment by zenker** [comment]
Ok

**Pull request merged**
